- name: varaible preferences
  hosts: local
  connection: local
  vars:
   my_number: 15
  tasks:
  - name: print if number greater than my number
    ansible.builtin.debug:
     msg: "Given number is {{ my_number }} is greater than 10"
    when: my_number > 10 

    
