- name: create ec2 instance
  hosts: local
  connection: local
  vars:
   subnet_id: subnet-0641e5abdbea94853
   ami_id: ami-0220d79f3f480ecf5
   sg_id: sg-01dd87a73633c63eb
   instance_type: t3_micro
   zone: udayops.online
   instances:
   - mysql
   - backend
   - frontend
  tasks:
   - name: Install AWS Python libraries
     ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
     loop:
     - boto3
     - botocore
   - name: create ec2 instances
     amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
     loop: "{{ instances }}"
     register: "{{ ec2_info }}"

   - name: print private address
     ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
     loop: "{{ ec2_info.results }}"

   - name: create r53 records
     amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
     loop: "{{ ec2_info.results }}"


   - name: create r53 records
     amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
     loop: "{{ ec2_info.results }}"
     when: item.item == "frontend"