- name: looping
  hosts: local
  connection: local
  tasks:
  - name: printing the loops
    ansible.builtin.package:
     name: "{{ item }}"
     state" present
    loop:
    - gcc
    - mysql
    - git
    - zip 

  