- name: varaible preferences
  hosts: local
  connection: local
  vars:
   GREET: PLAY
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREET
    prompt: Enter the value
    private: false

  tasks:
  - name: print the variable preferences
    vars:
     GREET: TASKS
    ansible.builtin.debug:
     msg: "Hi from {{ GREET }}"
